/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TanstackPageNameRouteImport } from './routes/tanstack.$pageName'

const TanstackPageNameRoute = TanstackPageNameRouteImport.update({
  id: '/tanstack/$pageName',
  path: '/tanstack/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/tanstack/$pageName': typeof TanstackPageNameRoute
}
export interface FileRoutesByTo {
  '/tanstack/$pageName': typeof TanstackPageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/tanstack/$pageName': typeof TanstackPageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tanstack/$pageName'
  fileRoutesByTo: FileRoutesByTo
  to: '/tanstack/$pageName'
  id: '__root__' | '/tanstack/$pageName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TanstackPageNameRoute: typeof TanstackPageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanstack/$pageName': {
      id: '/tanstack/$pageName'
      path: '/tanstack/$pageName'
      fullPath: '/tanstack/$pageName'
      preLoaderRoute: typeof TanstackPageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TanstackPageNameRoute: TanstackPageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
